"""
Compass Backend - Audit Database (SQLite)

This module provides a minimal audit log for compliance assessments.

Purpose:
- Persist every assessment input and output for traceability.
- Enable basic audit trails required in regulated environments.
- Keep storage simple (SQLite) for prototype speed and portability.

Notes:
- The database file is created under {project_root}/data/compass.db
- The data/ directory should be ignored by git (local runtime state).
"""

from __future__ import annotations

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


# Resolve project root and data directory
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
DB_PATH = DATA_DIR / "compass.db"


@dataclass(frozen=True)
class AssessmentRow:
    """
    Lightweight representation of an assessment row returned from SQLite.
    """
    assessment_id: str
    created_at: str
    policy_pack: str
    jurisdiction: str
    input_channel: str
    risk_level: str
    tags: List[str]
    input_excerpt: str

def _utc_now_iso() -> str:
    """
    Returns:
        str: Current UTC timestamp in ISO-8601 format.
    """
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def get_conn() -> sqlite3.Connection:
    """
    Open a SQLite connection, ensuring the data directory exists.

    Returns:
        sqlite3.Connection: Connection with Row factory enabled.
    """
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """
    Create the assessments audit table if it does not exist.

    Table design:
    - Store both input_text and full response JSON.
    - Store tags as JSON for easy inspection.
    - Primary key is assessment_id generated by the assessor.
    """
    conn = get_conn()
    cur = conn.cursor()
    
    

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS assessments (
            assessment_id TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            policy_pack TEXT NOT NULL,
            jurisdiction TEXT NOT NULL,
            input_channel TEXT NOT NULL,
            input_text TEXT NOT NULL,
            risk_level TEXT NOT NULL,
            tags_json TEXT NOT NULL,
            response_json TEXT NOT NULL
        )
        """
    )
    cur.execute(
    """
    CREATE TABLE IF NOT EXISTS review_decisions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        assessment_id TEXT NOT NULL,
        decision TEXT NOT NULL,
        reviewer TEXT NOT NULL,
        notes TEXT,
        decided_at TEXT NOT NULL,
        FOREIGN KEY (assessment_id) REFERENCES assessments(assessment_id)
    )
    """
)

    conn.commit()
    conn.close()


def save_assessment(
    *,
    assessment_id: str,
    policy_pack: str,
    jurisdiction: str,
    input_channel: str,
    input_text: str,
    risk_level: str,
    tags: Any,
    response: Dict[str, Any],
) -> None:
    """
    Persist an assessment record to the audit log.

    Parameters:
        assessment_id: Unique ID returned by the assessor.
        policy_pack: Policy pack name used for evaluation.
        jurisdiction: Jurisdiction used for evaluation.
        input_channel: Channel context, marketing, product, support.
        input_text: Raw text assessed.
        risk_level: LOW, MEDIUM, HIGH.
        tags: Tag list or set, will be JSON encoded.
        response: Full structured response, JSON encoded.

    This intentionally stores the full response payload so future changes
    to the response schema do not break historical records.
    """
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        """
        INSERT INTO assessments (
            assessment_id,
            created_at,
            policy_pack,
            jurisdiction,
            input_channel,
            input_text,
            risk_level,
            tags_json,
            response_json
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            assessment_id,
            _utc_now_iso(),
            policy_pack,
            jurisdiction,
            input_channel,
            input_text,
            risk_level,
            json.dumps(tags),
            json.dumps(response, default=str),
        ),
    )

    conn.commit()
    conn.close()


def list_recent_assessments(limit: int = 25) -> List[AssessmentRow]:
    """
    Return a small summary list of the most recent assessments.
    This is optional but useful for quick validation.

    Parameters:
        limit: Number of rows to return.

    Returns:
        List[AssessmentRow]: Summary rows.
    """
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        """
        SELECT assessment_id, created_at, policy_pack, jurisdiction, input_channel, risk_level, tags_json, input_text
        FROM assessments
        ORDER BY created_at DESC
        LIMIT ?
        """,
        (limit,),
    )

    rows = []
    for r in cur.fetchall():
        rows.append(
            AssessmentRow(
                assessment_id=r["assessment_id"],
                created_at=r["created_at"],
                policy_pack=r["policy_pack"],
                jurisdiction=r["jurisdiction"],
                input_channel=r["input_channel"],
                risk_level=r["risk_level"],
                tags=json.loads(r["tags_json"]),
                input_excerpt=(r["input_text"] or "")[:80],
            )
        )

    conn.close()
    return rows


def get_assessment_response(assessment_id: str) -> Optional[Dict[str, Any]]:
    """
    Fetch the stored response JSON for a given assessment_id.

    Returns:
        dict if found, else None.
    """
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        "SELECT response_json FROM assessments WHERE assessment_id = ?",
        (assessment_id,),
    )
    row = cur.fetchone()
    conn.close()

    if not row:
        return None

    return json.loads(row["response_json"])

def assessment_exists(assessment_id: str) -> bool:
    """
    Check whether an assessment exists in the audit log.
    Used to avoid recording decisions for unknown ids.
    """
    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        "SELECT 1 FROM assessments WHERE assessment_id = ? LIMIT 1",
        (assessment_id,),
    )
    row = cur.fetchone()
    conn.close()
    return row is not None


def save_review_decision(
    *,
    assessment_id: str,
    decision: str,
    reviewer: str,
    notes: str | None,
) -> Dict[str, Any]:
    """
    Save a human review decision for an assessment.

    Returns a dict representing the stored decision record.
    """
    conn = get_conn()
    cur = conn.cursor()

    decided_at = _utc_now_iso()
    cur.execute(
        """
        INSERT INTO review_decisions (
            assessment_id, decision, reviewer, notes, decided_at
        ) VALUES (?, ?, ?, ?, ?)
        """,
        (assessment_id, decision, reviewer, notes, decided_at),
    )

    conn.commit()
    conn.close()

    return {
        "assessment_id": assessment_id,
        "decision": decision,
        "reviewer": reviewer,
        "notes": notes,
        "decided_at": decided_at,
    }


def list_review_decisions(assessment_id: str, limit: int = 20) -> List[Dict[str, Any]]:
    """
    List review decisions for an assessment, newest first.
    """
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        """
        SELECT assessment_id, decision, reviewer, notes, decided_at
        FROM review_decisions
        WHERE assessment_id = ?
        ORDER BY decided_at DESC
        LIMIT ?
        """,
        (assessment_id, limit),
    )

    rows = []
    for r in cur.fetchall():
        rows.append(
            {
                "assessment_id": r["assessment_id"],
                "decision": r["decision"],
                "reviewer": r["reviewer"],
                "notes": r["notes"],
                "decided_at": r["decided_at"],
            }
        )

    conn.close()
    return rows